FROM --platform=linux/arm64 python:3.10-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    mlflow==3.12.0 \
    psycopg2-binary==2.9.9 \
    boto3==1.34.0 \
    gunicorn==21.2.0

EXPOSE 5000