FROM apache/airflow:2.10.5-python3.11

USER root
RUN apt-get update && apt-get install -y gcc g++ && apt-get clean

USER airflow
RUN pip install --no-cache-dir \
    duckdb \
    xgboost \
    scikit-learn \
    shap \
    pyarrow \
    boto3 \
    mlflow
